# Generated by Django 4.2 on 2025-01-11 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=160)),
                ('subtitle', models.TextField(db_index=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=160)),
                ('subtitle', models.TextField(db_index=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('subtitle', models.TextField(db_index=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_img', models.ImageField(db_index=True, upload_to='features')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('subtitle', models.CharField(db_index=True, max_length=150)),
                ('content', models.TextField(db_index=True, max_length=255)),
                ('ios_url', models.URLField(db_index=True)),
                ('app_store', models.ImageField(db_index=True, upload_to='header')),
                ('android_url', models.URLField(db_index=True)),
                ('google_market', models.ImageField(db_index=True, upload_to='header')),
                ('header_img', models.ImageField(db_index=True, upload_to='header')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(upload_to='team')),
                ('team_full_name', models.CharField(max_length=255)),
                ('team_position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_img', models.ImageField(upload_to='testimonials')),
                ('t_full_name', models.CharField(max_length=255)),
                ('t_role', models.CharField(max_length=255)),
                ('t_review', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=160)),
                ('video_url', models.URLField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('subtitle', models.CharField(db_index=True, max_length=500)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applight.featuresmain')),
            ],
        ),
    ]
