# Generated by Django 4.2 on 2025-01-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applight', '0003_about_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Video'},
        ),
    ]
