# Generated by Django 4.2 on 2025-01-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applight', '0005_features_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='delay',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
