# Generated by Django 4.2 on 2025-01-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applight', '0006_features_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applight.featuresmain'),
        ),
    ]
