# Generated by Django 4.2 on 2025-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applight', '0007_alter_features_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='delay',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
