# Generated by Django 4.2 on 2025-01-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applight', '0009_faq_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(db_index=True, max_length=160, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(db_index=True, max_length=160, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='features',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applight.featuresmain', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_index=True, max_length=160, verbose_name='title'),
        ),
    ]
